name: Update Leads

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run
        run: |
          python worldranking_downloader.py
          python taf.py --input leads/country --output leads/country/taf.csv
          python taf.py --input leads/world --output leads/world/taf.csv
          python taf.py --input leads/area --output leads/area/taf.csv
          git config user.name Github Action
          git config user.email actions@github.com
          git add leads/*/taf.csv
          timestamp=$(date -u)
          git commit -m "update leads data: ${timestamp}" || exit 0
          git push