name: Update Records

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run
        run: |
          python worldrecords.py
          python arearecords.py
          python nationalrecords.py
          python cleanup.py --input tmp/worldrecords
          python cleanup.py --input tmp/nationalrecords
          python cleanup.py --input tmp/arearecords
          python taf.py --input tmp/nationalrecords --output records/national.csv
          python taf.py --input tmp/worldrecords --output records/world.csv
          python taf.py --input tmp/arearecords --output records/europe.csv
          git config user.name Github Action
          git config user.email actions@github.com
          git add records/*
          timestamp=$(date -u)
          git commit -m "update records data: ${timestamp}" || exit 0
          git push